[workspace]
resolver = "2"

members = [
  "tupilities",
  "tupilities-clone",
  "tupilities-copy",
  "tupilities-debug",
  "tupilities-default",
  "tupilities-eq",
  "tupilities-hash",
  "tupilities-mut",
  "tupilities-option",
  "tupilities-ord",
  "tupilities-partial-eq",
  "tupilities-partial-ord",
  "tupilities-pop-front",
  "tupilities-pop-back",
  "tupilities-push-front",
  "tupilities-push-back",
  "tupilities-ref",
  "tupilities-derive",
]

[workspace.dependencies]
tupilities-clone = { path = "tupilities-clone" }
tupilities-copy = { path = "tupilities-copy" }
tupilities-debug = { path = "tupilities-debug" }
tupilities-default = { path = "tupilities-default" }
tupilities-eq = { path = "tupilities-eq" }
tupilities-hash = { path = "tupilities-hash" }
tupilities-mut = { path = "tupilities-mut" }
tupilities-option = { path = "tupilities-option" }
tupilities-ord = { path = "tupilities-ord" }
tupilities-partial-eq = { path = "tupilities-partial-eq" }
tupilities-partial-ord = { path = "tupilities-partial-ord" }
tupilities-pop-front = { path = "tupilities-pop-front" }
tupilities-pop-back = { path = "tupilities-pop-back" }
tupilities-push-front = { path = "tupilities-push-front" }
tupilities-push-back = { path = "tupilities-push-back" }
tupilities-ref = { path = "tupilities-ref" }
tupilities-derive = { path = "tupilities-derive" }
siphasher = { version = "1" }

[workspace.lints.rust]
missing_docs = "forbid"
unused_macro_rules = "forbid"
unconditional_recursion = "forbid"
unreachable_patterns = "forbid"
unused_import_braces = "forbid"
unused_must_use = "forbid"
deprecated = "deny"

[workspace.lints.clippy]
unreadable_literal = "allow"
missing_panics_doc = "allow"
new_ret_no_self = "allow"
struct_excessive_bools = "allow"
should_panic_without_expect = "allow"
doc_markdown = "allow"
unnecessary_cast = "forbid"
unused_unit = "allow"
redundant_clone = "forbid"
clone_on_copy = "forbid"
pedantic = { level = "deny", priority = -1 }
